const db= require('../db/index')
const {Games}= require('../models')

// Connect to the database
db.on('error', console.error.bind(console, 'MongoDB connection error:'))



const main = async () => {

    const games = [
        {
        consoleId: [ '65eb6b07c8b65edfb58066db', '65eb6b07c8b65edfb58066e0', ],
        title: 'Super Smash Bros. Ultimate',
        genre:[ 'Action, Fighting, 2D' ],
        year_released: 2014,
        description: 'Super Smash Bros. for Nintendo 3DS is the first portable entry in the renowned series, in which game worlds collide. Up to four players battle each other locally or online using some of Nintendos most well-known and iconic characters across beautifully designed stages inspired by classic portable Nintendo games. Its a genuine, massive Super Smash Bros. experience thats available to play on the go, anytime, anywhere.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/7/1/6/194716_front.jpg',
        number_of_players: '1-4',
        online: true,
        price: 29.96,
        rating: 'E',
      }, 
       {
        consoleId: [ '65eb6b07c8b65edfb58066db', '65eb6b07c8b65edfb58066e0' ],
        title: 'GoldenEye 007',
        genre:[ 'Action, Shooter, First-Person, Arcade' ],
        year_released: 2011,
        description: `Experience the GoldenEye game updated for the X360/PS3 with beautiful graphics, upgraded multiplayer capabilities, multiple controller types, and enhanced gameplay customizations.
        Refined. Recharged. Reloaded.
        
        True Next Gen - Experience GoldenEye on the next gen platform with stunning visuals, fast frenetic action, covert stealth gameplay and unforgettable characters.
        
        Upgraded Multiplayer - Replay the multiplayer game that defined a generation but, now, with all new enhancements:`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/6/7/5/198675_front.jpg',
        number_of_players: '1',
        online: true,
        price: 14.99,
        rating: 'T',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d7' ],
        title: 'Fable 2',
        genre:[ 'Role-Playing, Action RPG' ],
        year_released: 2008,
        description: 'Fable 2 is an action role-playing game that truly allows players to live the life they choose in an unimaginably open world environment. Set 500 years after the original, Fable 2 will provide gamers with an epic story and innovative real-time gameplay, including a massive amount of freedom and choice to explore a vast collection of dungeons, catacombs and caves in the world of Albion.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/9/5/7/66957_front.jpg',
        number_of_players: '1-2',
        online: true,
        price: 7.99,
        rating: 'M',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066da', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066e5', '65ee24dce1aef071e5d7668f' ],
        title: 'Fortnite',
        genre:[ 'Action, Shooter, Third-Person, Tactical' ],
        year_released: 2017,
        description: 'Fortnite is a third-person shooter game where up to 100 players compete to be the last person or team standing. You can compete alone or join a team of up to four. You progress through the game by exploring the island, collecting weapons, building fortifications and engaging in combat with other players.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/1/7/4/635174_front.jpg',
        number_of_players: '1',
        online: true,
        price: 0,
        rating: 'T',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066e4', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066d9', '65eb6b07c8b65edfb58066d8' ],
        title: 'Dark Souls',
        genre:[ 'Role-Playing, Action RPG' ],
        year_released: 2014,
        description: `The unique old-school action RPG experience captivated imaginations of gamers worldwide with incredible challenge and intense emotional reward. Dark Souls II brings the franchise's renowned difficulty & gripping gameplay innovations to both single and multiplayer experiences. Featuring increased texture resolution with enhanced frame rates. Dark Souls II on PC will support both gamepads and mouse-and-keyboard control options.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/7/3/4/363734_front.jpg',
        number_of_players: '1',
        online: false,
        price: 24.99,
        rating: 'T',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066da', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066e5', '65ee24dce1aef071e5d7668f' ],
        title: 'Persona 5 Royal',
        genre:[ 'Role-Playing, Action RPG' ],
        year_released: 2021,
        description: `Persona 5 is now an action RPG! The new action battle system makes hitting enemy weak points to activate a 1 More or All-Out Attack, which fans have come to love, even easier!`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/3/5/6/785356_front.jpg',
        number_of_players: '1',
        online: true,
        price: 14.99,
        rating: 'M',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066e2', '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066dc' ],
        title: 'Mortal Kombat 11',
        genre:[ 'Action, Fighting, 2D' ],
        year_released: 2019,
        description: 'Show off your skills and hold many fatalities in Mortal Kombat 11 Ultimate on PS5, the latest installment of this bone-crunching franchise. Choose between fighters like Mileena, Johnny Cage, Kitana, Rambo, and more. Players are provided with a deeper and more personalized experience than ever before with an all-new Custom Character Variation System. This allows gamers to have the creative control to customize versions of the entire character roster.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/2/5/8/694258_front.jpg',
        number_of_players: '1-2',
        online: true,
        price:27.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f' ],
        title: 'System Shock 2',
        genre:[ 'Action Adventure, Survival' ],
        year_released: 1999,
        description: 'You awake from the cold chill of your cryo-tube to discover cybernetic implants grafted to your flesh and the crew of the starship Von Braun slaughtered. The infected roam the halls, their screams and moans beckoning you to join them as the rogue artificial intelligence known as SHODAN taunts and ridicules your feeble attempt to unravel the horrifying mystery of the derelict starship Von Braun.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/0/2/7/1027_front.jpg',
        number_of_players: '1-2',
        online: false,
        price: 9.99,
        rating: 'M',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066da', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066e5', '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066dc' ],
        title: 'Resident Evil 2 (Remake)',
        genre:[ 'Action Adventure, Survival' ],
        year_released: 2019,
        description: `The genre-defining masterpiece Resident Evil 2 returns, completely rebuilt from the ground up for a deeper narrative experience. Using Capcom's proprietary RE Engine, Resident Evil 2 offers a fresh take on the classic survival horror saga with breathtakingly realistic visuals, heart-poundingly immersive audio, a new over-the-shoulder camera, and modernized controls on top of gameplay modes from the original game.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/3/1/9/676319_front.jpg',
        number_of_players: '1',
        online: false,
        price: 19.99,
        rating: 'M',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066e2', '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066dc' ],
        title: 'Monster Hunter: World',
        genre:[ 'Role-Playing, Action RPG' ],
        year_released: 2017,
        description: `Battle gigantic monsters in epic locales. As a hunter, you'll take on quests to hunt monsters in a variety of habitats. Take down these monsters and receive materials that you can use to create stronger weapons and armor in order to hunt even more dangerous monsters. In Monster Hunter: World, the latest installment in the series, you can enjoy the ultimate hunting experience, using everything at your disposal to hunt monsters in a new world teeming with surprises and excitement.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/1/2/2/634122_front.jpg',
        number_of_players: '1',
        online: false,
        price: 9.99,
        rating: 'T',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066dd', '65eb6b07c8b65edfb58066e3', '65ee24dce1aef071e5d7668f' ],
        title: `Tony Hawk's Pro Skater 2`,
        genre:[ 'Sports, Individual, Skate/Skateboard' ],
        year_released: 2000,
        description: `Hawk's back. And he's brought new pros (Caballero, Koston, Mullen). New tricks (Bluntsides, BS/FS Nose- and Tailsides, Heelflip Varials, Airwalks & more). And new terrain (insane street and very levels). Pro Skater 2 for Game Boy Color. Get your hands on a legend.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/3/1/3/8313_front.jpg',
        number_of_players: '1',
        online: false,
        price: 9.99,
        rating: 'E',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d7', '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066e4', '65ee24dce1aef071e5d7668f' ],
        title: 'Borderlands 2',
        genre:[ 'Action, Shooter, First-Person, Arcade' ],
        year_released: 2012,
        description: 'Borderlands 2 furthers the distinct blending of First Person Shooter and Role Playing genres to create the true evolution of the Role Playing Shooter. Team up with up to three other players for four-player online goodness or go old-school with two-player split-screen couch sharing mayhem as you spend hours leveling up your character and equipping them with one of the millions of badass weapons. Borderlands 2 features a new visually stunning array of procedurally generated guns, shields, grenades, artifacts, enemies and more. Choose one of the four new character classes to be taken through a carefully crafted and connected story to all new and surprising environments across the living planet of Pandora. Make new friends, arm them to the teeth and fight alongside them on your relentless quest for revenge and redemption.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/1/6/4/201164_front.jpg',
        number_of_players: '1-2',
        online: false,
        price: 9.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066d8' ],
        title: 'Titanfall 2',
        genre:[ 'Action, Shooter, First-Person, Arcade' ],
        year_released: 2016,
        description: `Pilot and Titan unite as never before in Respawn Entertainment's highly anticipated Titanfall® 2. Featuring a single player campaign that explores the unique bond between man and machine, and backed by a deeper multiplayer experience, Titanfall 2 delivers fast-paced action brimming with inventive twists.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/3/4/9/602349_front.jpg',
        number_of_players: '1',
        online: false,
        price: 6.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066d8' ],
        title: 'Inside',
        genre:[ 'Action, Platformer, 2D' ],
        year_released: 2016,
        description: 'Hunted and alone, a boy finds himself drawn into the center of a dark project.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/5/2/1/610521_front.jpg',
        number_of_players: '1',
        online: false,
        price: 12.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066e3', '65eb6b07c8b65edfb58066dd' ],
        title: 'SimCity 2000',
        genre:[ 'Strategy, Management, Government' ],
        year_released: 1993,
        description: `This morning, you approved a new solar power plant, designed an underground transportation system, and jumped five points in the polls. Then you raised taxes (and lost 10 points), read two local newspapers, built a zoo, a marina and a library, and pushed your education bill through the city council. It's time for lunch-unless, of course, there's a fire, tornado, earthquake or alien invasion... SimCity 2000 really brings your city-and its resident Sims-to life. If this game were any more realistic, it'd be illegal to turn it off.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/3/9/0/115390_front.jpg',
        number_of_players: '1',
        online: false,
        price: 10.99,
        rating: 'E',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f' ],
        title: 'Thief II: The Metal Age',
        genre:[ 'Action Adventure, General' ],
        year_released: 2000,
        description: `On the streets and rooftops of a darkened city, where the forces of a corrupt sheriff loom, it takes someone with a soft touch and even softer step to stay ahead of the law.
        For a master thief like Garrett, the choices are clear: profit or perish. Thief II: The Metal Age expands on the smash-hit "first-person sneaker", Thief: The Dark Project, demanding a whole new level of stealth, strategy, and skill to survive.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/2/0/6/1206_front.jpg',
        number_of_players: '1',
        online: false,
        price: 7.99,
        rating: 'T',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066dc' ],
        title: 'Animal Crossing: New Horizons',
        genre:[ 'Simulation, Virtual, Virtual Life' ],
        year_released: 2020,
        description: 'Escape to a deserted island and create your own paradise as you explore, create, and customize in the Animal Crossing: New Horizons game. Your island getaway has a wealth of natural resources that can be used to craft everything from tools to creature comforts. You can hunt down insects at the crack of dawn, decorate your paradise throughout the day, or enjoy sunset on the beach while fishing in the ocean. The time of day and season match real life, so each day on your island is a chance to check in and find new surprises all year round.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/4/5/3/973453_front.jpg',
        number_of_players: '1',
        online: true,
        price: 59.99,
        rating: 'E',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066e2', '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066dc' ],
        title: 'Divinity: Original Sin 2',
        genre:[ 'Role-Playing, Western-Style' ],
        year_released: 2017,
        description: 'Set a thousand years after the first game, Divinity: Original Sin II presents a darker, more grounded narrative and expands on the tactical combat system of its award-winning predecessor. In Divinity: Original Sin, you were on a quest for the forbidden Source magic. Now, you yourself are a Sourcerer: a dangerously powerful individual whose abilities summon creatures from the encroaching Void. The Divine is dead and the Void is everywhere.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/6/2/9/668629_front.jpg',
        number_of_players: '1-4',
        online: true,
        price: 34.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee2bd3c6a5308ebee04e2e' ],
        title: 'Mega Man 3',
        genre:[ 'Action, Platformer, 2D' ],
        year_released: 1990,
        description: `It's robot rebellion, and nobody's safe! Least of all, Mega Man! This time the superpowerful cyborg takes on a horde of metal maniacs who've had it with being obedient! And they use every android-annihilator ever invented to make you believe it! Mega Man goes berserk, blasting through a galaxy of mining stations in search of energy crystals. But it takes more than guts to battle the phenomenal robot masters who control these worlds. It's a wrenching job, the worst - and the best - that Mega Man's faced so far!`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/1/1/5/22115_front.jpg',
        number_of_players: '1',
        online: false,
        price: 27.99,
        rating: 'N/A',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f' ],
        title: 'League of Legends',
        genre:[ 'Strategy, Real-Time, MOBA' ],
        year_released: 2009,
        description: `A player in League of Legends takes on the role of a Summoner - a gifted spell caster who has the power to bring forth a champion to fight as his or her avatar in Valoran's Fields of Justice. As the Summoner controls the champion in combat, it also influences the outcome of the match through the use of spells, masteries and runes. Once a match is over, the Summoner gains Influence Points and Riot Points that can be used to assist their champions in future battles.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/6/7/4/105674_front.jpg',
        number_of_players: '1-10',
        online: true,
        price: 0,
        rating: 'T',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f' ],
        title: 'Fallout 2',
        genre:[ 'Role-Playing, Western-Style' ],
        year_released: 1998,
        description: `Fallout 2 is the sequel to the critically acclaimed game that took RPG'ing out of the dungeons and into a dynamic, apocalyptic retro-future. It's been 80 long years since your ancestor trod across the wastelands. As you search for the Garden of Eden Creation Kit to save your primitive village, your path is strewn with crippling radiation, megalomaniac mutants, and a relentless stream of lies, deceit and treachery.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/4/9/2/492_front.jpg',
        number_of_players: '1',
        online: false,
        price: 4.99,
        rating: 'M',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066e1', '65eb6b07c8b65edfb58066d9' ],
        title: 'Burnout 3: Takedown',
        genre:[ 'Racing, Arcade, Automobile' ],
        year_released: 2004,
        description: 'Burnout 3 challenges you to crash into (and through) busy intersections, while creating as much damage as possible. You can battle your way to the front of the pack by taking down rivals and causing spectacular crashes. For those who thirst for crashes, the game includes a crash mode that rewards you for creating massive pileups. With multiplayer gameplay, more than 100 events, and 40 tracks, Burnout 3 provides intense speed and action.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/2/9/7/58297_front.jpg',
        number_of_players: '1-2',
        online: true,
        price: 9.99,
        rating: 'T',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f' ],
        title: `Monkey Island 2: LeChuck's Revenge`,
        genre:[ 'Adventure, Point-and-Click' ],
        year_released: 1991,
        description: `In LeChuck's Revenge Guybrush Threepwood returns in his search for the legendary treasure of Big Whoop. He is now a genuine pirate and has traded in his white shirt and clean shaved face for a dashing blue coat and a beard. This would not be a true sequel if we did not see the return of the villain LeChuck and so, in the true spirit of Monkey Island, Guybrush accidentally helps to bring back LeChuck who, of course, wants revenge. The game itself has evolved much since the original. It feels about four times bigger and includes four different islands.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/7/6/8/19768_front.jpg',
        number_of_players: '1',
        online: false,
        price: 14.99,
        rating: 'N/A',
      },  {
        consoleId: [ '65eb6b07c8b65edfb58066d7', '65eb6b07c8b65edfb58066d8', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066e4', '65eb6b07c8b65edfb58066e0', '65ee24dce1aef071e5d7668f' ],
        title: `Assassin's Creed IV: Black Flag`,
        genre:[ 'Action Adventure, Open-World' ],
        year_released: 2013,
        description: 'It is 1715. Pirates rule the Caribbean and have established a lawless pirate republic. Among these outlaws is a fearsome young captain named Edward Kenway. His exploits earn the respect of pirate legends like Blackbeard, but draw him into an ancient war that may destroy everything the pirates have built.',
        img_path: 'https://gamefaqs.gamespot.com/a/box/5/8/1/271581_front.jpg',
        number_of_players: '1',
        online: true,
        price: 11.99,
        rating: 'M',
      },  {
        consoleId: [ '65ee24dce1aef071e5d7668f', '65eb6b07c8b65edfb58066e3', '65eb6b07c8b65edfb58066e2', '65eb6b07c8b65edfb58066dc', '65eb6b07c8b65edfb58066d8' ],
        title: 'Final Fantasy VII',
        genre:[ 'Role-Playing, Japanese-Style' ],
        year_released: 1997,
        description: `Mako—the discovery of this natural resource drawn directly from the planet's life force marked the dawn of a new era, and now the energy sustains the lives of people across the world. However, the Shinra Company has monopolized mako production, and in doing so established a powerful hegemony--its influence reaching the far corners of the globe.`,
        img_path: 'https://gamefaqs.gamespot.com/a/box/7/8/5/785_front.jpg',
        number_of_players: '1',
        online: false,
        price: 11.99,
        rating: 'T',
      },
      ]

    await Games.insertMany(games)
    console.log("Created some Games!")
}
const run = async () => {
    await main()
    db.close()
}

run()
