const db= require('../db/index')
const {Games}= require('../models')

// Connect to the database
db.on('error', console.error.bind(console, 'MongoDB connection error:'))



const main = async () => {

    const games=[
// {
//         consoleId: ['65eb6b07c8b65edfb58066db','65eb6b07c8b65edfb58066dc'],
//         Title: 'EarthBound',
//         Genre: 'Role-Playing ',
//         Year_Released: 1995,
//         Description: 'An open-world game set in the American Old West, following outlaw Arthur Morgans adventures in the dying Wild West era',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/6/9/50669_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: No,
//         Price: 59.99,
//         Rating:'E',
//     } ,  {
//         consoleId: ['65eb6b07c8b65edfb58066d7'],
//         Title: 'Left 4 Dead 2',
//         Genre: 'First-person shooter, Survival horror ',
//         Year_Released: 2009,
//         Description: 'Left 4 Dead 2 came out exactly a year after the original, which upset a lot of people who (incorrectly) assumed the sequel would be a glorified expansion pack to the first. But Left 4 Dead 2 does exactly what a sequel needs to do: be better in every way. L4D2 - developed in-house at Valve - has more creative levels in its campaign, more special infected to kill (or play as, if playing in Versus Mode), a bigger variety of weapons, and protagonists with some actual personality. ',
//         Image_Path: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Left4Dead2.jpg/220px-Left4Dead2.jpg',
//         Number_of_Players: 'Single-player,multiplayer',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'E',
//     } ,  {
//         consoleId: ['65eb6b07c8b65edfb58066d9'],
//         Title: 'Counter-Strike 1.6',
//         Genre: ' Action',
//         Year_Released: 2000,
//         Description:'Many of the things I value most in skill-based games, I value because of Counter-Strike: good level design, team-based dynamic, the dedication required to master it, a friendly sense of competition, and a solid sense of community. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/7/5/9/11759_front.jpg',
//         Number_of_Players: 'multiplayer',
//         Online: Yes,
//         Price: 24.99,
//         Rating: 'E',
//     } ,   {
//         consoleId: ['65eb6b07c8b65edfb58066d8',],
//         Title: 'Ms. Pac-Man',
//         Genre: ' Action',
//         Year_Released: 1982,
//         Description:'Many of the things I value most in skill-based games, I value because of Counter-Strike: good level design, team-based dynamic, the dedication required to master it, a friendly sense of competition, and a solid sense of community. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/0/4/8/31048_front.jpg',
//         Number_of_Players: 'multiplayer',
//         Online: Yes,
//         Price: 39.99,
//         Rating:'E',
//     } , {
//         consoleId: ['65eb6b07c8b65edfb58066dc',],
//         Title: 'Hollow Knight',
//         Genre: 'Metroidvania',
//         Year_Released: 2017,
//         Description:'In a genre as old as the Metroidvania, its rare for a game to breathe fresh life into it as much as Hollow Knight did. Its winding subterranean halls are deeper than you’d expect in just about every way you can imagine – from its impressive size and scope, to its comprehensive but delicately told story and lore, to its innumerable upgrades and secrets to uncover.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/9/5/2/685952_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 44.99,
//         Rating: 'E',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066da','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e5'],
//         Title: 'Apex Legends',
//         Genre: 'Tactical',
//         Year_Released: 2019,
//         Description:'Apex Legends continues to bring one of if not the best free-to-play Battle Royale to fans, and its shining accomplishment may just lie in its revolutionary ping system. Its ability to give players the capability to instantly and efficiently communicate in the middle of hectic yet strategic battles is one of the most impactful innovations in gaming.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/7/3/701673_front.jpg',
//         Number_of_Players: 'Multiplayer',
//         Online: Yes,
//         Price: 7.99,
//         Rating: 'E',
//     } ,
//     {
//         consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066da','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e5'],
//         Title: 'Overwatch',
//         Genre: 'Tactical',
//         Year_Released:  2016,
//         Description:'Blizzard performed alchemy here. Overwatch should be leaden – a Team Fortress cover version with two-and-a-half modes and a MOBA approach to character design. And yet what we have is gold. The key here is in how Blizzard looked beyond simply making a good shooter – it made an interesting one. Its backstory is PG-13 Pixar, its characters are diverse and lovable, and much more. Pro gamers, cosplayers, fanfic writers, ARG detectives and everyone in between have all been given a reason to play a single game – no mean feat. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/8/3/0/607830_front.jpg',
//         Number_of_Players: 'Multiplayer',
//         Online: Yes,
//         Price: 0.99,
//         Rating: 'M',
//     } , {
//         consoleId: ['65eb6b07c8b65edfb58066e4'],
//         Title: 'Uncharted 2: Among Thieves',
//         Genre: 'Action-adventure, third-person shooter',
//         Year_Released:  2009,
//         Description:'Many games attempt to emulate cinema, dealing in the same tropes and stock characters. Initially, it looks like Uncharted does the same thing – it focuses on a treasure hunter who frequently finds himself in danger across exotic locations. But when you play Uncharted, especially the second installment, Among Thieves, you realize it surpasses much of Hollywood with ease.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/0/6/106606_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 44.99,
//         Rating: 'M',
//     } , {
//         consoleId: ['65eb6b07c8b65edfb58066e4'],
//         Title: 'Journey',
//         Genre: 'Action ',
//         Year_Released:  2012,
//         Description:'Many games attempt to emulate cinema, dealing in the same tropes and stock characters. Initially, it looks like Uncharted does the same thing – it focuses on a treasure hunter who frequently finds himself in danger across exotic locations. But when you play Uncharted, especially the second installment, Among Thieves, you realize it surpasses much of Hollywood with ease.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/2/1/3/157213_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 44.99,
//         Rating: 'E',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8'],
//         Title: 'The Witness',
//         Genre: 'Adventure ',
//         Year_Released:  2016,
//         Description:'The island setting of The Witness enveloped me in its striking color palette and minimalistic soundscape. Weaved into this tranquil setting however is a series of fiendish puzzles, each offering a unique challenge. These puzzles had me scrawling patterns on pieces of graph paper, reflecting the sun, and listening to the local wildlife – I explored every corner of my brain, and this island, in search of increasingly-evasive solutions. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/1/2/123612_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 39.99,
//         Rating: 'E',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8'],
//         Title: 'Dishonored 2',
//         Genre: 'Action-adventure, stealth ',
//         Year_Released:  2016,
//         Description:'Dishonored 2’s wildly fun skillset is perfectly paired with its chaotic playground; tinkering with both means no two playthroughs will ever be the same. Bend Dishonored 2, try and break it, and you’ll be amazed and how deeply it caters to your most deranged experimentation. Like its predecessor, it’s also incredibly stylish, the Southern-European city of Karnaca bursting with ideas and history. Play it low-key, and Dishonored 2 is one of the best stealth games ever made.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/1/2/123612_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 39.99,
//         Rating: 'M',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066dc',],
//         Title: 'Batman: Arkham City',
//         Genre: 'Action-adventure ',
//         Year_Released:  2011,
//         Description:'After Arkham Asylum laid the groundwork for a superhero game that hit all the right beats, Batman: Arkham City took everything to the next level by letting Batman loose in the streets of Gotham. Not only did it nail the feeling of stalking and beating down thugs with an impressive array of gadgets, it raised the stakes of what a caped crusader could deal with in a single night. Arkham City’s heaping helping of infamous rogues let you experience them in their element, and found perfect ways for Batman to foil them via both brain and brawn – leading to some of the best boss fights ever conceived.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/0/3/4/136034_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 9.99,
//         Rating:'T',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066dc',],
//         Title: 'Rise of the Tomb Raider',
//         Genre: 'Action-adventure ',
//         Year_Released:  2016,
//         Description:'While the Tomb Raider reboot in 2013 kicked off a new direction for the iconic heroine that was more in line with modern AAA storytelling (read: Lara was given a deeper backstory and a personality), Rise of the Tomb Raider took it and ran a mile. It continued to flesh out Lara as a driven, wary character while upping the ante on what made the 2013 game so fun; fluid traversal, crunchy combat, and beautifully intricate puzzle tombs. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/8/0/1/624801_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 14.99,
//         Rating: 'M',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e0'],
//         Title: 'Call of Duty 4: Modern Warfare',
//         Genre: 'First-person shooter ',
//         Year_Released:  2007,
//         Description:'All Ghillied Up was my first glimpse of Call of Duty 4: Modern Warfare in action, and as two camouflaged snipers worked their way through an irradiated Pripyat in Ukraine, I was instantly hooked. The highlight – not just of the demo but arguably of the entire game – was watching, breath held, as an entire armored patrol trundled past, inches from our hiding spot, and it’s a moment of tension that’s never been matched in a shooter since.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/4/5/5/85455_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'M',
//     } ,{
//         consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e5'],
//         Title: 'Control',
//         Genre: 'Action-adventure',
//         Year_Released:  2019,
//         Description:'Ostensibly a drab government building, Controls main setting of The Oldest House is actually a shifting, twisting, and teleporting behemoth, which the team uses to consistently marry the everyday with the supernatural in increasingly bizarre and exciting ways. And exploration around this world is some of the best in third-person action - Marvel may not have ever given us a proper Jean Grey videogame, but playing as Jesse Faden offers enough telekinetic powers to play with that at once feel powerful and spry, weighty yet nimble in a way that translates to both exploration and combat. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/8/3/8/706838_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'M',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066dc',],
//         Title: ' XCOM 2',
//         Genre: 'Turn-based tactics, tactical role-playing',
//         Year_Released:  2016,
//         Description:'Kicking alien invaders off of Earth in XCOM 2: War of the Chosen never gets old. Thanks to its procedurally generated maps and wide range of enemies, abilities, and ever-improving gear and weaponry, the tactical possibilities for your squad are all but endless. Especially when played on high difficulty in the no-takebacks Iron Man mode, every decision can mean the difference between life and permadeath for characters who begin as blank slate rookies but become an elite team. (And thats before you even get started on mods.) ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/8/4/613684_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 17.99,
//         Rating: 'T',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066e1','65eb6b07c8b65edfb58066e4','65eb6b07c8b65edfb58066d9'],
//         Title: 'Grand Theft Auto: San Andreas',
//         Genre: 'Action-adventure',
//         Year_Released:  2016,
//         Description:'Perhaps the most remarkable thing about Grand Theft Auto: San Andreas is just how much it dwarfs Grand Theft Auto III in every way. Forget one city. Have three, with vast swathes of forests, countryside, and desert in between. Want more vehicles? Have over 250 of them, including jump jets, combine harvesters, lawnmowers, bicycles, semi-trailers, forklifts, and so, so many more. Music? No problem. How does 11 radio stations and over 150 tracks sound? Not enough? How about a functioning casino? How about a jetpack? ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/8/4/613684_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 19.99,
//         Rating: 'M',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d9','65eb6b07c8b65edfb58066e1',],
//         Title: 'Silent Hill 2',
//         Genre: 'Survival horror',
//         Year_Released:  2011,
//         Description:'Silent Hill 2 was the first in the series to establish the town itself as a character – in a genre oversaturated with run-of-the-mill killers, zombies, aliens, and other more conventional adversaries, Silent Hill 2’s focus on horror in architecture, in the layout and personality of a space, of the human psyche turned tangible, was vastly more interesting to me. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/9/6/9/11969_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 69.99,
//         Rating: 'RP',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066dd',],
//         Title: 'Super Mario World 2: Yoshis Island',
//         Genre: 'Platform',
//         Year_Released:  2011,
//         Description:'In this era of Trophies and Achievements, completing everything in a game is common. But when Yoshi’s Island came out, the reward for exploration was greater than a Gamerscore: for collecting all of the extremely well-hidden red coins and flowers and then finishing a level with 30 stars (which basically means you can’t get hit), you received a 100% rating. If you did this on every level in a world, you unlocked two more levels in each of the six worlds.',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/3/1/8/51318_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 34.99,
//         Rating: 'E',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066de','65eb6b07c8b65edfb58066db','65eb6b07c8b65edfb58066d9','65eb6b07c8b65edfb58066e4','65eb6b07c8b65edfb58066e1'],
//         Title: 'Splinter Cell: Chaos Theory',
//         Genre: 'Stealth',
//         Year_Released:  2011,
//         Description:'Sam Fishers third adventure is actually three masterpiece games in one. In the campaign, a stunning real-time lighting engine and open mission design allows you to play in countless different ways: total stealth, full gunplay, or a gadget-fest. Game 2 is the four-mission two-player co-op campaign, in which two young agents work together in a side story that runs parallel to Fishers adventure. You literally have to play together, from boosting each other up to high ledges to going back-to-back to scale elevator shafts, the co-op mode committed to cooperation in a way no other action game had. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/3/9/3/60393_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'E',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066db','65eb6b07c8b65edfb58066de','65eb6b07c8b65edfb58066e4','65eb6b07c8b65edfb58066e1'],
//         Title: 'The Sims 3',
//         Genre: 'Social simulation',
//         Year_Released:  2009,
//         Description:'The Sims 3 was a fantastic leap forward in the franchise, showcasing what a more open and customizable base version of The Sims could look like. While the Sims 4 has grown significantly in the years its been out, its base version (and especially its launch version) lacked in items, features, and general options compared to The Sims 3. If were looking at each game from their base features and even expansions, The Sims 3 simply did more despite having more simplified actions and Sims emotions. ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/2/1/7/81217_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 4.99,
//         Rating: 'T',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066db','65eb6b07c8b65edfb58066de','65eb6b07c8b65edfb58066e4','65eb6b07c8b65edfb58066e1'],
//         Title: 'Donkey Kong',
//         Genre: 'Platform',
//         Year_Released:  1981,
//         Description:'When you walk into a room full of arcade games, something looks different about Donkey Kong. Its pastel blue cabinet is a bit shorter than the others; a bit rounder, more welcoming. The glowing marquee and art on the game depicts characters that belong on a 1960s pizza delivery box. When you put a quarter in, the machine shows you a little cartoon of an ape clambering up a ladder, mocking you.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/0/2/4/3024_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 44.99,
//         Rating: 'E',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066e0','65eb6b07c8b65edfb58066dc'],
//         Title: 'Mario Kart 8 Deluxe',
//         Genre: 'Kart racing',
//         Year_Released:  2014,
//         Description:'Mario Kart 8 Deluxe may be a re-release of the original Wii U kart racer, but its function is as both a fantastic kart racer in its own right and a more complete package of an already great game. Its selection of classic and brand new tracks make for an excellent rotation of races that keeps things fresh no matter how much you play with a thorough roster of racers and plenty of kart customization options.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/4/7/8/398478_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'E',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e2'],
//         Title: 'Return of the Obra Dinn',
//         Genre: 'Adventure, puzzle',
//         Year_Released:  2013,
//         Description:'It’s easy to underestimate Return of the Obra Dinn at first glance. A 1-bit game about being an insurance evaluator on an empty boat may not light your heart ablaze, but that simple shell houses one of the most clever, captivating, and unfalteringly impressive puzzle games you’ll ever play. It’s a mystery game that empowers its players to actually solve its otherworldly cold cases for themselves, relying on the real detective work of observation and deduction to uncover its secrets rather than highlighted objects and scripted set pieces.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/6/3/2/728632_front.jpg',
//         Number_of_Players: 'Single-player',
//         Online: Yes,
//         Price: 9.99,
//         Rating: 'E',
//     } ,{
//         consoleId: [,'65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066e2'],
//         Title: 'Spelunky 2',
//         Genre: 'Platform, roguelike',
//         Year_Released:  2020,
//         Description:'Both the original freeware version of Spelunky, and its 2008 HD remake are two of the most influential games of all time due to their monumental impact that shaped the entire roguelike genre. The HD remake was largely viewed as being a near perfect game, in particular. That is, until Spelunky 2 came along 12 years later and somehow managed to improve upon every single facet of its mechanics without ever sacrificing the procedurally generated magic that made Spelunky so special.  ',
//         Image_Path: 'https://gamefaqs.gamespot.com/a/box/3/1/5/780315_front.jpg',
//         Number_of_Players: 'Single-player, multiplayer',
//         Online: Yes,
//         Price: 59.99,
//         Rating: 'E',
//     } ,
{
    consoleId: ['65eb6b07c8b65edfb58066e2','65eb6b07c8b65edfb58066e5'],
    title: 'God of War',
    genre: ['Action', 'RPG'],
    year_released: 2018,
    description: 'Embark on a mythic journey for answers and allies before Ragnarök arrives in God of War Ragnarok on PS5. Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. Against a backdrop of Norse Realms torn asunder by the fury of the Aesir, they’ve been trying their utmost to undo the end times. But despite their best efforts, Fimbulwinter presses onward. Witness the changing dynamic of the father-son relationship as they fight for survival; Atreus thirsts for knowledge to help him understand the prophecy of “Loki”, as Kratos struggles to break free of his past and be the father his son needs.',
    img_path: 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
    number_of_players: "1",
    online: false,
    price: 37.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066db'],
    title: 'Metal Gear Solid 3: Snake Eater',
    genre: ['Action'],
    year_released: 2018,
    description: 'In the aftermath of the Second World War, the world was torn in two between East and West. It was the beginning of a new era- the Cold War.',
    img_path: 'https://i5.walmartimages.com/seo/Restored-Metal-Gear-Solid-Snake-Eater-3D-Nintendo-3DS-2011-Refurbished_d68187e5-ae15-4ee6-86da-9d507a0c8b1b.80f22b07777d196c57fb6074b8281842.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF',
    number_of_players: "1",
    online: true,
    price: 54.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066dc', '65eb6b07c8b65edfb58066e5',],
    title: 'Doom',
    genre: ['Action', 'Shooter'],
    year_released: 2018,
    description: "You've come here for a reason. The Union Aerospace Corporation's massive research facility on Mars is overwhelmed by fierce and powerful demons, and only one person stands between their world and ours. As the lone DOOM Marine, you've been activated to do one thing – kill them all.",
    img_path: 'https://preview.redd.it/who-is-the-artist-for-the-alternate-2016-doom-cover-art-v0-eti4s76gkbt81.jpg?auto=webp&s=eb5888e5a4144a95bb9ca10799a2b9c5a38f29c9',
    number_of_players: "1",
    online: true,
    price: 4.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d8',],
    title: ' Final Fantasy XIV',
    genre: ['RPG'],
    year_released: 2013,
    description: "Join over 27 million adventurers worldwide and take part in an epic and ever-changing FINAL FANTASY. Experience all the hallmarks of the best-selling franchise - an unforgettable story, exhilarating battles, and a myriad of diverse and captivating environments to explore. Party up with friends or play solo! Experience all the main story dungeons on your own by calling upon NPC allies to fight by your side.",
    img_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMlhYB_6FKzffLiSs_N1EcnxcqHnYfl5MjSSy-FjtPFioH_536kE_oJFFLIrkMBjy7zPs&usqp=CAU',
    number_of_players: '1',
    online: true,
    price: 19.99,
    rating: 'T',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d9',],
    title: ' Half-Life 2',
    genre: ['RPG'],
    year_released: 2004,
    description: "Half-Life revolutionized first-person shooters and set into motion the adventures of Gordon Freeman. Half-Life 2 for the Xbox continues Gordon's story and introduces him to the Combine, a multidimensional empire that took over Earth. Gordon joins a resistance force to combat the Combine and finds himself facing off against a familiar alien foe. Use an arsenal of weapons to stop the Combine from its complete conquest over humanity.",
    img_path: "https://media.gamestop.com/i/gamestop/10152637/Half-Life-2---Xbox?$pdp2x$$&fmt=webp",
    number_of_players: '1',
    online: false,
    price: 9.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d7'],
    title: 'Halo: Combat Evolved',
    genre: ['Action'],
    year_released: 2013,
    description: "Halo: Combat Evolved Anniversary is a spectacularly remastered version of the original “Halo” campaign, created in celebration of the 10th anniversary of one of the most beloved franchises in gaming history. With a bounty of new features including cooperative play over Xbox LIVE, a bundle of some of the most beloved multiplayer maps in “Halo” history reimagined for Xbox LIVE, new challenges and a new story to uncover, Halo: Anniversary is a must-have experience.",
    img_path: 'https://media.gamestop.com/i/gamestop/10091401/Halo-Combat-Evolved-Anniversary---Xbox-360?$pdp2x$$&fmt=webp',
    number_of_players: "1-4",
    online: true,
    price: 9.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d7', '65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066dc','65eb6b07c8b65edfb58066de','65eb6b07c8b65edfb58066e2','65eb6b07c8b65edfb58066e5'],
    title: 'Minecraft',
    genre: ['Simulation'],
    year_released: 2011,
    description: "Minecraft is a game about placing blocks and going on adventures. Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armor to fend off the dangerous mobs.",
    img_path: 'https://xxboxnews.blob.core.windows.net/prod/sites/2/XboxOne_Minecraft-Box-Art_Square-Image.png',
    number_of_players: "1-4",
    online: true,
    price: 27.99,
    rating: 'E',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066df'],
    title: 'Metroid Prime',
    genre: ['Action'],
    year_released: 2005,
    description: "Samus first stopped the evil Space Pirates and Mother Brain from amassing an army of Metroids on the planet Zebes. Then she was called on to finish the job on SR388, ultimately ridding the universe of all but a single Metroid larva. In Super Metroid, for the Super Nintendo Entertainment System, Samus thwarted Mother Brain's attempt to snatch the captive Metroid larva from the scientists on Ceres. Now, Samus is once again called to investigate Space Pirate activities on the unexplored Tallon IV. Her adventure begins as she enters a mysterious derelict spaceship.",
    img_path: 'https://media.gamestop.com/i/gamestop/10020498/Metroid-Prime---GameCube?$pdp2x$$&fmt=webp',
    number_of_players: '1',
    online: false,
    price: 19.99,
    rating: 'T',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066de'],
    title: 'The Legend of Zelda: Ocarina of Time',
    genre: ['Action'],
    year_released: 2011,
    description: "The Legend of Zelda™: Ocarina of Time™ 3D brings a completely re-mastered version of this epic entry in the beloved The Legend of Zelda series to the Nintendo 3DS system. The game couples phenomenally enhanced graphics with stunning glasses-free 3D visuals to bring to life the daring adventures of its hero, Link™, in the epic tale of the creation of Hyrule and the struggle for control of its all-powerful ancient relic. A streamlined touch-screen interface and new motion controls give the game a fresh and intuitive feel. The game will also feature new challenges not included in the original game, as well as a new hint system to help novice players experience all that the game has to offer. The Legend of Zelda: Ocarina of Time 3D is a masterful improvement on one of the landmark moments in video gaming history.",
    img_path: 'https://media.gamestop.com/i/gamestop/10128747/Nintendo-Selects-The-Legend-of-Zelda-Ocarina-of-Time-3D---Nintendo-3DS?$pdp2x$$&fmt=webp',
    number_of_players: '1',
    online: true,
    price: 39.99,
    rating: 'E',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d9'],
    title: 'Metal Gear Solid',
    genre: ['Adventure'],
    year_released: 1998,
    description: "Guide Solid Snake, an elite government agent, through this tense cinematic saga as he attempts to regain control of a nuclear weapons base from terrorist hands. Lightly armed and facing an army of foes, you must stay silent and in the shadows to avoid direct enemy contact as enemies intelligently react to sight and sound.",
    img_path: 'https://media.gamestop.com/i/gamestop/10122347/Metal-Gear-Solid---PlayStation?$pdp2x$$&fmt=webp',
    number_of_players: '1',
    online: true,
    price: 27.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066da'],
    title: "Sid Meier's Civilization IV",
    genre: ['Simulation'],
    year_released:2005 ,
    description: "Originally created by legendary game designer Sid Meier, Civilization is a turn-based strategy game in which you attempt to build an empire to stand the test of time. Explore a new land, research technology, conquer your enemies, and go head-to-head with history's most renowned leaders as you attempt to build the greatest civilization the world has ever known.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/7/7e/CivIVboxshot.jpg',
    number_of_players: '1-4',
    online: true,
    price: 17.99,
    rating: 'E',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066e2','65eb6b07c8b65edfb58066e5', '65eb6b07c8b65edfb58066da'],
    title: 'Resident Evil 4',
    genre: ['Horror'],
    year_released: 2023,
    description: "Resident Evil™ 4 joins Leon S. Kennedy six years after his hellish experiences in the biological disaster of Raccoon City. His unmatched resolve caused him to be recruited as an agent reporting directly to the president of the United States. With the experience of multiple missions on his back, Leon is dispatched to rescue the president’s recently kidnapped daughter. Leon tracks her to a secluded European village, however, after making first contact he discovers a fervor beyond reason grips the local populace. Now, this reimagined tale of survival in the face of overwhelming terror returns to deliver a visually stunning modern gaming experience that is true to the promise of the original release.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/d/df/Resident_Evil_4_remake_cover_art.jpg',
    number_of_players: '1',
    online: true,
    price: 39.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066e4'],
    title: 'Red Dead Redemption',
    genre: ['Action'],
    year_released: 2010,
    description: "Winner of over 100 Game of the Year awards including Spike Video Game Awards, Machinima Inside Gaming Awards, GameSpot, Games Radar, Spin, CNET, Associated Press and NY Post.America, 1911. The Wild West is dying. When federal agents threaten his family, former outlaw John Marston is forced to pick up his guns again and hunt down the gang of criminals he once called friends. Experience an epic fight for survival across the sprawling expanses of the American West and Mexico, as John Marston struggles to bury his bloodstained past, one man at a time.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Red_Dead_Redemption.jpg',
    number_of_players: '1',
    online: false,
    price: 14.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d8','65eb6b07c8b65edfb58066da','65eb6b07c8b65edfb58066dc', '65eb6b07c8b65edfb58066e5','65eb6b07c8b65edfb58066e2'],
    title: 'The Elder Scrolls V: Skyrim',
    genre: ['RPG'],
    year_released: 2013,
    description: "Skyrim® brings to life a complete virtual world for you to explore any way you choose, including all-new features like motion controls, plus outfits and gear from compatible The Legend of Zelda™ amiibo. Take down enemies with the Master Sword, protect yourself with the Hylian Shield or look heroic in the Champion’s Tunic. The legendary freedom of choice and adventure of Skyrim is realized like never before. Dragons, long lost to the passages of the Elder Scrolls, have returned and the future of Skyrim hangs in the balance. As Dragonborn, the prophesized hero born with the power of The Voice, you are the only one who can stand amongst them.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
    number_of_players: '1',
    online: true,
    price: 49.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066e2'],
    title: 'The Last of Us Part 2',
    genre: ['Action'],
    year_released: 2020,
    description: "In Last of Us Part II follow Ellie and Joel while they settle down in Jackson, Wyoming. Five years after their dangerous journey across post-pandemic America, they live amongst a community of survivors. In this community they have found peace and stability, but still remember the constant threat of the infected and not so friendly survivors.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/TLOU_P2_Box_Art_2.png/220px-TLOU_P2_Box_Art_2.png',
    number_of_players: '1',
    online: true,
    price: 29.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066dd',],
    title: ' Pokémon Yellow',
    genre: ['RPG'],
    year_released: 1998,
    description: "You've finally been granted your Pokemon trainer's license, and now you're on your way to becoming the world's greatest Pokemon trainer! The shockingly cute Pikachu tags along behind you as you search the enormous world for monsters to train and evolve. Face off against Blastoise's torrential water gun. Stand strong when facing Pidgeot's stormy gust. Develop the ultimate Pokemon strategy to defeat the eight GYM leaders and become the greatest Pokemon master of all time!",
    img_path: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c9be30e5-5d79-4c7e-b734-3ce0a28bb294/d9tkttk-0b29809e-087a-4436-b31f-76ca60ea0f61.png/v1/fill/w_900,h_900,q_80,strp/pokemon_yellow_version__game_boy__hq_box_art_clean_by_jadelune_d9tkttk-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTAwIiwicGF0aCI6IlwvZlwvYzliZTMwZTUtNWQ3OS00YzdlLWI3MzQtM2NlMGEyOGJiMjk0XC9kOXRrdHRrLTBiMjk4MDllLTA4N2EtNDQzNi1iMzFmLTc2Y2E2MGVhMGY2MS5wbmciLCJ3aWR0aCI6Ijw9OTAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.Q6ukEeqDs7jl0iepMLt0yFhAxCZAmcMDuILFbGp2gOQ',
    number_of_players: '1',
    online: false,
    price: 100,
    rating: 'E',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d7','65eb6b07c8b65edfb58066e4'],
    title: 'Fallout: New Vegas',
    genre: ['RPG'],
    year_released: 2010,
    description: "Welcome to Vegas. New Vegas. It's the kind of town where you dig your own grave prior to being shot in the head and left for dead…and that's before things really get ugly. It's a town of dreamers and desperados being torn apart by warring factions vying for complete control of this desert oasis. It's a place where the right kind of person with the right kind of weaponry can really make a name for themselves, and make more than an enemy or two along the way.As you battle your way across the heat-blasted Mojave Wasteland, the colossal Hoover Dam, and the neon drenched Vegas Strip, you'll be introduced to a colorful cast of characters, power-hungry factions, special weapons, mutated creatures and much more. Choose sides in the upcoming war or declare “winner takes all” and crown yourself the King of New Vegas in this follow-up to the 2008 videogame of the year, Fallout 3.Enjoy your stay.",
    img_path: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Fallout_New_Vegas.jpg/220px-Fallout_New_Vegas.jpg',
    number_of_players: '1',
    online: false,
    price: 4.99,
    rating: 'M',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066e2',],
    title: 'Shadow of the Colossus',
    genre: ['Action'],
    year_released: 2018,
    description: "Rebuilt from the ground up by Bluepoint Games and Japan Studio, Shadow Of The Colossus on PlayStation 4 system introduces the awe of its unforgettable world and towering creatures to a new generation of gamers, while allowing longtime fans to revisit the beloved masterpiece with unparalleled visual fidelity and improved performance.",
    img_path: 'https://media.gamestop.com/i/gamestop/10149676/Shadow-of-the-Colossus---PlayStation-4?$pdp2x$$&fmt=webp',
    number_of_players: '1',
    online: true,
    price: 19.99,
    rating: 'T',
  },
  {
    consoleId: ['65eb6b07c8b65edfb58066d9'],
    title: 'Star Wars: Knights of the Old Republic',
    genre: ['Action'],
    year_released: 2003,
    description: "Long before the Galactic Civil War, an epic drama begins. Engage in this saga set in the Golden Age of the Republic - over 4,000 years before the first Star Wars film, when both Jedi and Sith number in the thousands. With the Galaxy reeling from a recent conflict with the Dark Lords, the ongoing battle between the Jedi and the Sith rages on. Your actions determine the outcome of this colossal galactic war - and your destiny as a Jedi.",
    img_path: 'https://howlongtobeat.com/games/250px-Kotorbox.jpg?width=250',
    number_of_players: '1',
    online: true,
    price: 4.99,
    rating: 'T',
  }

    ]

    await Games.insertMany(games)
    console.log("Created some Games!")
}
const run = async () => {
    await main()
    db.close()
}

run()
